[package]
name = "gepub"
version = "0.1.0"
authors = ["Antoni Boucher <bouanto@zoho.com>"]

[dependencies]
glib = "0.10.3"
glib-sys = "0.10"
gobject-sys = "0.10"
gtk = "0.9.2"

[dev-dependencies]
gio = "0.9.1"

[dependencies.gepub-sys]
path = "./gepub-sys"
