// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

mod archive;
pub use self::archive::{Archive, ArchiveClass};

mod doc;
pub use self::doc::{Doc, DocClass};

mod text_chunk;
pub use self::text_chunk::{TextChunk, TextChunkClass, NONE_TEXT_CHUNK};
pub use self::text_chunk::TextChunkExt;

mod widget;
pub use self::widget::{Widget, WidgetClass};

#[doc(hidden)]
pub mod traits {
    pub use super::TextChunkExt;
}
