// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#[cfg(not(feature = "dox"))]
extern crate system_deps;

#[cfg(not(feature = "dox"))]
use std::process;

#[cfg(feature = "dox")]
fn main() {} // prevent linking libraries to avoid documentation failure

#[cfg(not(feature = "dox"))]
fn main() {
    let result = system_deps::Config::new()
        .add_build_internal("gepub_0_6", |lib, version| {
            system_deps::Library::from_internal_pkg_config("libgepub-0.6.pc", "libgepub-0.6", version)
        })
        .probe();
    if let Err(s) = result {
        let _ = eprintln!("{}", s);
        process::exit(1);
    }
}
